id = "hjson"
name = "HJSON"
version = "0.0.1"
schema_version = 1
authors = ["Pascal d'Achard contact.pascaldachard@gmail.com"]
description = "HJSON language support for Zed"
repository = "https://github.com/your-name/my-zed-extension"

[grammars.hjson]
repository = "https://github.com/winston0410/tree-sitter-hjson"
commit = "02fa3b79b3ff9a296066da6277adfc3f26cbc9e0"
path = "."
