name = "HJSON"
grammar = "hjson"
path_suffixes = ["hjson"]
line_comments = ["# ", "// "]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
